src/config/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from students.views import index


handler404 = "templates.errors.views.error_404"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", index, name="index"),
]

urlpatterns += [
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    re_path(
        r"^media/(?P<path>.*)$",
        serve,
        {
            "document_root": settings.MEDIA_ROOT,
        },
    ),
]

src/groups/urls.py
from django.urls import path

from groups.views import get_groups, create_group, update_group, delete_group

app_name = "groups"

urlpatterns = [
    path("", get_groups, name="get_group"),
    path("create/", create_group, name="create_group"),
    path("update/<int:pk>/", update_group, name="update_group"),
    path("delete/<int:pk>/", delete_group, name="delete_group"),
]

src/groups/models.py
from django.db import models
from faker import Faker


class Group(models.Model):
    name = models.CharField(max_length=120, blank=True, null=True)
    max_students = models.PositiveSmallIntegerField(default=20, null=True)
    start_date = models.DateField(blank=True, null=True)
    count_of_lessons = models.PositiveSmallIntegerField(default=32, null=True)
    speciality = models.CharField(max_length=120, blank=True, null=True)
    address_lessons = models.CharField(max_length=120, blank=True, null=True)

    @classmethod
    def generate_groups(cls, count: int) -> None:
        faker = Faker()
        for i in range(count):
            group = Group(
                name=faker.company(),
                max_students=faker.random_int(min=1, max=20),
                start_date=faker.future_date(end_date="+30d"),
                count_of_lessons=faker.random_int(min=1, max=32),
                speciality=faker.job(),
                address_lessons=faker.address(),
            )
            group.save()

    def __str__(self):
        return f"{self.name} {self.start_date} {self.max_students} {self.speciality} ({self.id})"

src/groups/forms.py
from django.forms import ModelForm

from groups.models import Group


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ["name", "max_students", "start_date", "count_of_lessons", "speciality", "address_lessons"]

src/groups/views.py
from django.db.models import Q
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from webargs import fields
from webargs.djangoparser import use_args

from groups.forms import GroupForm
from groups.models import Group


@use_args(
    {
        "name": fields.Str(required=False),
        "speciality": fields.Str(required=False),
        "search": fields.Str(required=False),
    },
    location="query",
)
def get_groups(request: HttpRequest, params) -> HttpResponse:
    groups = Group.objects.all()
    search_fields = ["name", "speciality", "start_date"]
    for param_name, param_value in params.items():
        if param_name == "search":
            or_filter = Q()
            for field in search_fields:
                or_filter |= Q(**{f"{field}__contains": param_value})
                groups = groups.filter(or_filter)
        else:
            groups = groups.filter(**{param_name: param_value})
    return render(request, template_name="list_group.html", context={"groups": groups})


@csrf_exempt
def create_group(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("groups:get_group"))
    elif request.method == "GET":
        form = GroupForm()
    return render(request, template_name="create_group.html", context={"form": form})


@csrf_exempt
def update_group(request: HttpRequest, pk: int) -> HttpResponse:
    group = get_object_or_404(Group.objects.all(), pk=pk)

    if request.method == "POST":
        form = GroupForm(request.POST, instance=group)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("groups:get_group"))
    elif request.method == "GET":
        form = GroupForm(instance=group)
    return render(request, template_name="update_group.html", context={"form": form})


@csrf_exempt
def delete_group(request: HttpRequest, pk: int) -> HttpResponse:
    group = get_object_or_404(Group.objects.all(), pk=pk)

    if request.method == "GET":
        group.delete()
        return HttpResponseRedirect(reverse("groups:get_group"))

src/groups/templates/create_group.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post" style="width: 25em; margin: auto">
        {{ form|crispy }}
        <input type="submit" class="btn btn-success" value="Create">
    </form>
{% endblock content %}

src/groups/templates/list_group.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <table class="table table-dark table-striped-columns">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Students</th>
            <th scope="col">Start Date</th>
            <th scope="col">Count of lessons</th>
            <th scope="col">Speciality</th>
            <th scope="col">Address</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {% for group in groups %}
            <tr>
                <th scope="row">{{ group.pk }}</th>
                <td>{{ group.name }}</td>
                <td>{{ group.max_students }}</td>
                <td>{{ group.start_date }}</td>
                <td>{{ group.count_of_lessons }}</td>
                <td>{{ group.speciality }}</td>
                <td>{{ group.address_lessons }}</td>
                <td>
                    <a type="button" class="btn btn-primary"
                       href="{% url 'groups:update_group' group.pk %}">Edit</a>
                </td>
                <td>
                    <a type="button" class="btn btn-primary"
                       href="{% url 'groups:delete_group' group.pk %}">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

src/groups/templates/update_group.html
{% extends 'index.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post" style="width: 25em; margin: auto">
        {{ form|crispy }}
        <input type="submit" class="btn btn-success" value="Update">
    </form>
{% endblock content %}