src/config/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from students.views import index


handler404 = "templates.errors.views.error_404"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", index, name="index"),
]

urlpatterns += [
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    re_path(
        r"^media/(?P<path>.*)$",
        serve,
        {
            "document_root": settings.MEDIA_ROOT,
        },
    ),
]

src/teachers/urls.py
from django.urls import path
from teachers.views import get_teachers, create_teacher, update_teacher, delete_teacher

app_name = "teachers"

urlpatterns = [
    path("", get_teachers, name="get_teachers"),
    path("create/", create_teacher, name="create_teacher"),
    path("update/<int:pk>/", update_teacher, name="update_teacher"),
    path("delete/<int:pk>/", delete_teacher, name="delete_teacher"),
]

src/teachers/models.py
from decimal import Decimal

from django.db import models
from faker import Faker


class Teacher(models.Model):
    first_name = models.CharField(max_length=120, blank=True, null=True)
    last_name = models.CharField(max_length=120, blank=True, null=True)
    email = models.EmailField(max_length=120)
    phone_number = models.CharField(max_length=120, blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    rating = models.DecimalField(decimal_places=2, max_digits=3, default=0)

    @classmethod
    def generate_teachers(cls, count: int) -> None:
        faker = Faker()
        for i in range(count):
            teacher = Teacher(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                phone_number=faker.phone_number(),
                birth_date=faker.date_of_birth(minimum_age=16, maximum_age=60),
                rating=Decimal(faker.pydecimal(min_value=0, max_value=5, right_digits=2)),
            )
            teacher.save()

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.phone_number} {self.rating} ({self.id})"

src/teachers/forms.py
from django.forms import ModelForm

from teachers.models import Teacher


class TeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = ["first_name", "last_name", "email", "phone_number", "birth_date"]

src/teachers/views.py
from django.db.models import Q
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from webargs import fields
from webargs.djangoparser import use_args

from teachers.forms import TeacherForm
from teachers.models import Teacher


@use_args(
    {
        "first_name": fields.Str(required=False),
        "last_name": fields.Str(required=False),
        "search": fields.Str(required=False),
    },
    location="query",
)
def get_teachers(request: HttpRequest, params) -> HttpResponse:
    teachers = Teacher.objects.all()
    search_fields = ["first_name", "last_name", "email", "phone_number"]
    for param_name, param_value in params.items():
        if param_name == "search":
            or_filter = Q()
            for field in search_fields:
                or_filter |= Q(**{f"{field}__contains": param_value})
                teachers = teachers.filter(or_filter)
        else:
            teachers = teachers.filter(**{param_name: param_value})
    return render(request, template_name="list_teacher.html", context={"teachers": teachers})


@csrf_exempt
def create_teacher(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = TeacherForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("teachers:get_teachers"))
    elif request.method == "GET":
        form = TeacherForm()

    return render(request, template_name="create_teacher.html", context={"form": form})


@csrf_exempt
def update_teacher(request: HttpRequest, pk: int) -> HttpResponse:
    teacher = get_object_or_404(Teacher.objects.all(), pk=pk)

    if request.method == "POST":
        form = TeacherForm(request.POST, instance=teacher)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("teachers:get_teachers"))
    elif request.method == "GET":
        form = TeacherForm(instance=teacher)

    return render(request, template_name="update_teacher.html", context={"form": form})


@csrf_exempt
def delete_teacher(request: HttpRequest, pk: int) -> HttpResponse:
    teacher = get_object_or_404(Teacher.objects.all(), pk=pk)

    if request.method == "GET":
        teacher.delete()
        return HttpResponseRedirect(reverse("teachers:get_teachers"))

src/teachers/templates/create_teacher.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post" style="width: 25em; margin: auto">
        {{ form|crispy }}
        <input type="submit" class="btn btn-success" value="Create">
    </form>
{% endblock content %}

src/teachers/templates/list_teacher.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <table class="table table-dark table-striped-columns">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Phone number</th>
            <th scope="col">Birth date</th>
            <th scope="col">Rating</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {% for teacher in teachers %}
            <tr>
                <th scope="row">{{ teacher.pk }}</th>
                <td>{{ teacher.first_name }}</td>
                <td>{{ teacher.last_name }}</td>
                <td>{{ teacher.email }}</td>
                <td>{{ teacher.phone_number }}</td>
                <td>{{ teacher.rating }}</td>
                {% if teacher.birth_date %}
                    <td>{{ teacher.birth_date }}</td>
                {% else %}
                    <td>Unknown</td>
                {% endif %}
                <td>
                    <a type="button" class="btn btn-primary"
                       href="{% url 'teachers:update_teacher' teacher.pk %}">Edit</a>
                </td>
                <td>
                    <a type="button" class="btn btn-primary"
                       href="{% url 'teachers:delete_teacher' teacher.pk %}">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

src/teachers/templates/update_teacher.html
{% extends 'index.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post" style="width: 25em; margin: auto">
        {{ form|crispy }}
        <input type="submit" class="btn btn-success" value="Update">
    </form>
{% endblock content %}