src/config/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from students.views import index


handler404 = "templates.errors.views.error_404"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", index, name="index"),
]

urlpatterns += [
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    re_path(
        r"^media/(?P<path>.*)$",
        serve,
        {
            "document_root": settings.MEDIA_ROOT,
        },
    ),
]

src/students/urls.py
from django.urls import path

from students.views import get_students, create_student, update_student, delete_student

app_name = "students"

urlpatterns = [
    path("", get_students, name="get_students"),
    path("create/", create_student, name="create_student"),
    path("update/<int:pk>/", update_student, name="update_student"),
    path("delete/<int:pk>/", delete_student, name="delete_student"),
]

src/students/models.py
import datetime

from django.db import models
from faker import Faker


class Student(models.Model):
    first_name = models.CharField(max_length=120, blank=True, null=True)
    last_name = models.CharField(max_length=120, blank=True, null=True)
    email = models.EmailField(max_length=120)
    grade = models.PositiveSmallIntegerField(default=0, null=True)
    birth_date = models.DateField(blank=True, null=True)

    def age(self):
        return datetime.datetime.now().year - self.birth_date.year

    @classmethod
    def generate_students(cls, count: int) -> None:
        faker = Faker()
        for i in range(count):
            student = Student(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                birth_date=faker.date_of_birth(minimum_age=16, maximum_age=60),
            )
            student.save()

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.email} ({self.id})"

src/students/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from students.models import Student


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ["first_name", "last_name", "email", "birth_date"]

    @staticmethod
    def normalize_text(text):
        return text.strip().capitalize()

    def clean_first_name(self):
        return self.normalize_text(self.cleaned_data["first_name"])

    def clean_last_name(self):
        return self.normalize_text(self.cleaned_data["last_name"])

    def clean_email(self):
        email = self.cleaned_data["email"]

        if "@yandex" in email:
            raise ValidationError("This email not use.")

        return email

    def clean_birth_date(self):
        return self.cleaned_data["birth_date"]

src/students/views.py
from django.db.models import Q
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt


from students.forms import StudentForm
from students.models import Student


def index(request: HttpRequest) -> HttpResponse:
    return render(request, template_name="../templates/index.html", context={"name": "LMS"})


def get_students(request):
    search_query = request.GET.get("search", None)

    students = Student.objects.all()
    search_fields = ["first_name", "last_name", "email", "birth_date"]
    if search_query:
        or_filter = Q()
        for field in search_fields:
            or_filter |= Q(**{f"{field}__contains": search_query})
        students = students.filter(or_filter)
    return render(request, template_name="list.html", context={"students": students})


@csrf_exempt
def create_student(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("students:get_students"))
    elif request.method == "GET":
        form = StudentForm()

    return render(request, template_name="create.html", context={"form": form})


@csrf_exempt
def update_student(request: HttpRequest, pk: int) -> HttpResponse:
    student = get_object_or_404(Student.objects.all(), pk=pk)

    if request.method == "POST":
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("students:get_students"))
    elif request.method == "GET":
        form = StudentForm(instance=student)
    return render(request, template_name="update.html", context={"form": form})


@csrf_exempt
def delete_student(request: HttpRequest, pk: int) -> HttpResponse:
    student = get_object_or_404(Student.objects.all(), pk=pk)

    if request.method == "GET":
        student.delete()
        return HttpResponseRedirect(reverse("students:get_students"))

src/students/templates/create.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post" style="width: 25em; margin: auto">
        {{ form|crispy }}
        <input type="submit" class="btn btn-success" value="Create">
    </form>
{% endblock content %}

src/students/templates/list.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block content %}
<nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
  <div class="container-fluid">
    <form class="d-flex" role="search" method="GET" action="{% url 'students:get_students' %}">
      {% csrf_token %}
      <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search">

      <button class="navbar bg-dark border-bottom border-body" type="submit">Search</button>
    </form>
  </div>
</nav>
    <table class="table table-dark table-striped-columns">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Grade</th>
            <th scope="col">Birth date</th>
            <th scope="col">Age</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>
                <th scope="row">{{ student.pk }}</th>
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.grade }}</td>
                {% if student.birth_date %}
                    <td>{{ student.birth_date }}</td>
                    <td>{{ student.age }}</td>
                {% else %}
                    <td>Unknown</td>
                    <td>Unknown</td>
                {% endif %}
                <td>
                    <a type="button" class="btn btn-primary"
                       href="{% url 'students:update_student' student.pk %}">Edit</a>
                </td>
                <td>
                    <a type="button" class="btn btn-primary"
                       href="{% url 'students:delete_student' student.pk %}">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

src/students/templates/update.html
{% extends 'index.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post" style="width: 25em; margin: auto">
        {{ form|crispy }}
        <input type="submit" class="btn btn-success" value="Update">
    </form>
{% endblock content %}